### ISSUE TITLE
SwiftUI Example does not build

### ISSUE THREAD

**Issue by te-ch99** [AgoraIO-Community/VideoUIKit-iOS#91]
Error - Missing package product 'AgoraRtmControl'

**Comment by maxxfrazer** [comment]
Thanks for reporting that, will take a look as soon as possible. If you need to get an example running sooner, just try commenting out that line. Feel free to open a PR if that fixes it too.

Otherwise, there's a separate open source SwiftUI library that's being worked on now that's a bit more swiftui-friendly: https://github.com/AgoraIO-Community/AgoraVideoSwiftUI
